Repository epsagon/epsagon-go, pull requests merged in 2020-11, with the labels that each got.

#73 Gin wrapper
  epsagon/generic_wrapper.go
  epsagon/generic_wrapper_test.go
  example/gin_wrapper/main.go
  example/gin_wrapper/makefile
  go.mod
  go.sum
  tracer/mocked_tracer.go
  tracer/tracer.go
  wrappers/gin/gin.go
  wrappers/gin/gin_test.go
Labels: size/L

#74 Gin trigger event
  README.md
  epsagon/aws_v2_wrapper.go
  epsagon/common_utils.go
  epsagon/generic_wrapper.go
  epsagon/generic_wrapper_test.go
  epsagon/tracer_helpers.go
  example/gin_wrapper/main.go
  tracer/mocked_tracer.go
  tracer/tracer.go
  wrappers/aws/aws-sdk-go/aws/aws.go
  wrappers/gin/gin.go
  wrappers/gin/gin_test.go
  wrappers/net/http/client.go
  wrappers/net/http/client_test.go
Labels: size/XL

#76 Adding custom labels as a strong key
  tracer/tracer.go
Labels: size/XS

#77 adding ignored keys support for masking metadata keys
  README.md
  example/ignored_keys/main.go
  tracer/mask_ignored_keys.go
  tracer/mask_ignored_keys_test.go
  tracer/mocked_tracer.go
  tracer/tracer.go
Labels: size/L

#78 fix README mistake
  README.md
Labels: size/XS

#80 Fix gin resource type
  epsagon/generic_wrapper.go
  example/gin_wrapper/main.go
  tracer/mocked_tracer.go
  wrappers/gin/gin.go
  wrappers/gin/gin_test.go
Labels: size/M

#81 created shortcut for router.Run
  example/gin_wrapper/main.go
  go.sum
  wrappers/gin/gin.go
Labels: size/M

#83 Adding target ARN support for SNS
  wrappers/aws/aws-sdk-go/aws/aws_test.go
  wrappers/aws/aws-sdk-go/aws/sns_factory.go
Labels: size/M
