Repository epsagon/epsagon-go, pull requests merged in 2020-10, with the labels that each got.

#54 added TracingTransport for http.Client
  README.md
  epsagon/concurrent_generic_wrapper_test.go
  example/api_gateway/main.go
  example/concurrent_generic_go_functions/main.go
  wrappers/net/http/client.go
  wrappers/net/http/client_test.go
Labels: size/L

#57 Update README.md
  README.md
Labels: size/XS

#58 Wrappable TracingTransport; lazy tracer setting in RoundTrip
  README.md
  wrappers/net/http/client.go
  wrappers/net/http/client_test.go
Labels: size/M

#60 increasing to v1.8.0
  tracer/version.go
Labels: size/XS

#59 Marshal the return value of lambda functions
  epsagon/lambda_wrapper.go
  example/api_gateway/serverless.yml
Labels: size/S

#61 Formatting headers - taking first header value
  wrappers/net/http/client.go
Labels: size/S

#62 Adding github action to auto-increment version in code
  .github/workflows/main.yml
Labels: size/M

#63 Fixing extracted tracer checks
  internal/tracer_helpers.go
Labels: size/XS

#65 Update main.yml
  .github/workflows/main.yml
Labels: size/XS

#66 Increasing version
  tracer/version.go
Labels: size/XS

#67 Update main.yml
  .github/workflows/main.yml
Labels: size/XS

#68 Fix version workflow
  .github/workflows/main.yml
Labels: size/S

#64 Labels error ut ep 4688
  epsagon/common_utils.go
  epsagon/concurrent_generic_wrapper_test.go
  epsagon/custom_trace_data_test.go
  tracer/tracer.go
Labels: size/L

#69 get global tracer each time
  wrappers/net/http/client.go
Labels: size/M

#71 Update main.yml
  .github/workflows/main.yml
Labels: size/XS

#70 do not truncate response to caller
  wrappers/net/http/client.go
Labels: size/XS

#72 Adding metadata trimming
  .travis.yml
  epsagon/custom_trace_data_test.go
  tracer/tracer.go
  wrappers/net/http/client.go
  wrappers/net/http/client_test.go
Labels: size/L
